### ISSUE TITLE
can I make the different widgets show different colors for the same measured value

### ISSUE THREAD

**Issue by dksam** [cloud4rpi/cloud4rpi-raspberrypi-python#8]
can I make the different widgets show different colors for the same measured value (for example CPU temperature, I want to show a different color in the gauge, and a different color in the graph, thanks, (Cloud4RPi is really insanely great so thanks)

**Comment by sky3d** [comment]
Thank you for your interest in our product. You can specify user-defined color for each series in a chart widget. Unfortunately, a gauge widget does not provide this feature for now. We will consider your suggestion.
